import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import LeftSidebar from "@/components/shared/LeftSidebar";
import RightSidebar from "@/components/shared/RightSidebar";
import BottomBar from "@/components/shared/BottomBar";
import NavbarDemo from "@/components/shared/NavbarDemo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "THREADS",
  description: "Next js app generated by HYMANSHU",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavbarDemo />
          <main className="flex bg-yellow-500 h-screen">
            <LeftSidebar />
            <section className="flex-grow bg-yellow-800 ml-[15%] mr-[18%] p-4">
              {children}
            </section>
            <RightSidebar />
          </main>
          <BottomBar />
        </body>
      </html>
    </ClerkProvider>
  );
}
