
import {ClerkProvider} from "@clerk/nextjs"
import { Inter } from "next/font/google";
export const metadata = {
  title: "THREADS",
  description: "Next js app generated by HYMANSHU",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en">
            <body className={`${inter.className} bg-black`}>
              
                {children}
            </body>
        </html>
    </ClerkProvider>
    
  );
}
